#!/usr/bin/env python3
"""Generate C++17 resources, preserving the input files byte for byte."""

import argparse
from pathlib import Path


def cpp_string(data):
    # Fixed-width octal escapes handle arbitrary encodings, NULs and delimiters
    # without depending on the compiler's source character set.
    return '"' + ''.join(f'\\{byte:03o}' for byte in data) + '"'


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--root', type=Path, required=True)
    parser.add_argument('--output', type=Path, required=True)
    parser.add_argument('files', type=Path, nargs='+')
    args = parser.parse_args()
    root = args.root.resolve()
    files = sorted((path.resolve() for path in args.files),
                   key=lambda path: path.relative_to(root).as_posix())

    lines = [
        '// Generated by scripts/embed_vhdl.py. Do not edit.',
        '#include "embedded_vhdl.h"',
        '#include <stdexcept>',
        '#include <string>',
        '',
        'namespace embedded_vhdl {',
        'namespace {',
    ]
    for index, path in enumerate(files):
        data = path.read_bytes()
        lines.append(f'constexpr char resource_{index}[] =')
        lines.extend(cpp_string(data[offset:offset + 64])
                     for offset in range(0, len(data), 64))
        lines.append('"";')
    lines.extend([
        'const std::vector<resource> resources = {',
    ])
    for index, path in enumerate(files):
        name = cpp_string(path.relative_to(root).as_posix().encode('utf-8'))
        lines.append(f'    {{{name}, {{resource_{index}, sizeof(resource_{index}) - 1}}}},')
    lines.extend([
        '};',
        '} // namespace',
        '',
        'const std::vector<resource>& all() { return resources; }',
        '',
        'std::string_view get(std::string_view name) {',
        '    for (const auto& entry : resources)',
        '        if (entry.name == name)',
        '            return entry.contents;',
        '    throw std::out_of_range("Unknown embedded VHDL resource: " + std::string(name));',
        '}',
        '} // namespace embedded_vhdl',
        '',
    ])
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text('\n'.join(lines), encoding='ascii')


if __name__ == '__main__':
    main()
